name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build x64
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore and Build Solution for x64
      run: |
        msbuild "GH Injector Library.sln" /p:Configuration=Release /p:Platform=x64 /m

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Binaries-x64
        path: |
          GH Injector Library/GH Injector Library/bin/x64/Release/*
          GH Injector SM/GH Injector SM/bin/x64/Release/*
          GH Injector DNP/GH Injector DNP/bin/x64/Release/*
